# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f003a2ffdb59fba1565ec685cbc679c48825d54d897dd8940828f8c5feccbe1d9ec481e982ab03db99f26c3a5dd95c4778206bf2740c5d747489c9bbcd5c32c0

test:
  secret_key_base: 56a9987365a98d587f97e8f980eec2ea6e81e083cdc90b85333281abbdc7e2adb47d675a68361904f864e608e55e0636bd6727522a14ad154f691abf0ecdd915

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
